apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-configmap
    files:
      - ../../nginx/nginx.conf

resources:
  - deployment.yaml
  - configMap.yaml